services:
  db:
    env_file: .env
    image: postgres:latest
    environment:
      POSTGRES_DB: tasker
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  tasker:
    env_file: .env
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tasker
      DB_USER: postgres
    links:
      - db

volumes:
  pgdata:

    